### PR TITLE
Fix php 7.0 exif error

### PR DESCRIPTION
**Pull request by netsnatch**

### CODE REVIEW

**Comment by netsnatch** [comment]
Fix exif error

**Comment by adityapatadia** [comment]
What exactly is error with PHP 7.0?

**Comment by netsnatch** [comment]
exif_read_data(853509.jpeg): Illegal IFD size

**Comment by adityapatadia** [comment]
It must be something specific with that image. Closing this as of now as it is not a widespread issue with library.

**Pull request closed without merging**
